// Generated by tools/build_images.py. Do not edit.
export const IMAGES = {
  "alma-tadema": {
    "aspect": 1.8286,
    "variants": [
      {
        "w": 480,
        "avif": "assets/paintings/alma-tadema-480.2d92b3ac.avif",
        "webp": "assets/paintings/alma-tadema-480.be71d390.webp"
      },
      {
        "w": 960,
        "avif": "assets/paintings/alma-tadema-960.2b1a2f98.avif",
        "webp": "assets/paintings/alma-tadema-960.1cec2582.webp"
      },
      {
        "w": 1024,
        "avif": "assets/paintings/alma-tadema-1024.c32e7a4e.avif",
        "webp": "assets/paintings/alma-tadema-1024.a9b79584.webp"
      }
    ],
    "thumb": "assets/paintings/alma-tadema-thumb.b039e98e.webp",
    "depth": "assets/paintings/alma-tadema-depth.523c0ec7.webp"
  },
  "altar": {
    "aspect": 1.3989,
    "variants": [
      {
        "w": 480,
        "avif": "assets/paintings/altar-480.6bdfe077.avif",
        "webp": "assets/paintings/altar-480.160a3856.webp"
      },
      {
        "w": 960,
        "avif": "assets/paintings/altar-960.c2593fb0.avif",
        "webp": "assets/paintings/altar-960.ebeb2a16.webp"
      },
      {
        "w": 1024,
        "avif": "assets/paintings/altar-1024.d60c2789.avif",
        "webp": "assets/paintings/altar-1024.e5ee666f.webp"
      }
    ],
    "thumb": "assets/paintings/altar-thumb.000f4710.webp",
    "depth": "assets/paintings/altar-depth.a1a2aa30.webp"
  },
  "godward": {
    "aspect": 1.2468,
    "variants": [
      {
        "w": 480,
        "avif": "assets/paintings/godward-480.4867fd25.avif",
        "webp": "assets/paintings/godward-480.396d4f0e.webp"
      },
      {
        "w": 960,
        "avif": "assets/paintings/godward-960.3730b20c.avif",
        "webp": "assets/paintings/godward-960.95a0f112.webp"
      },
      {
        "w": 1600,
        "avif": "assets/paintings/godward-1600.777e5d1e.avif",
        "webp": "assets/paintings/godward-1600.ad6743d4.webp"
      },
      {
        "w": 2400,
        "avif": "assets/paintings/godward-2400.4f7f349e.avif",
        "webp": "assets/paintings/godward-2400.b7d206b4.webp"
      }
    ],
    "thumb": "assets/paintings/godward-thumb.b85f74fc.webp",
    "depth": "assets/paintings/godward-depth.8b4f9e4f.webp"
  },
  "leap": {
    "aspect": 0.8,
    "variants": [
      {
        "w": 480,
        "avif": "assets/paintings/leap-480.39342402.avif",
        "webp": "assets/paintings/leap-480.aef56b7c.webp"
      },
      {
        "w": 960,
        "avif": "assets/paintings/leap-960.b4bd221b.avif",
        "webp": "assets/paintings/leap-960.5b911c30.webp"
      }
    ],
    "thumb": "assets/paintings/leap-thumb.451de45d.webp",
    "depth": "assets/paintings/leap-depth.c71e2782.webp"
  }
};
