"""Parser candidates for a standalone word lookup (/api/word), as in-poem analysis does.

When the source index has no exact analysis of a form, the machine-morphology service
(local Morpheus when configured) is asked about the form, and, if it knows nothing,
about the standard spellings generated by backend.dialect_generate. Each parse becomes a
display candidate with its lemma, a readable parse, the engine that produced it, the
generated spelling and rules when there is one, and the lemma's dictionary gloss chosen
exactly as for passage rows (backend.lemma_glosses). Nothing here is a source record.
"""
from __future__ import annotations

MAX_ROWS = 12


def parser_candidates(form, machine_service, headword_lookup=None, form_lemmas=None):
    from .dialect_generate import describe, generate_and_test
    from .interlinear import canonical_features, compact_parse
    from .machine_morphology import engine_label, local_endpoint

    result = machine_service.analyze(form, None, fetch=False)
    found = []
    if result.get("status") == "ok" and result.get("machine_candidates"):
        found = [(None, (), result)]
    elif result.get("status") == "no_analyses":
        try:
            local = bool(local_endpoint())
        except ValueError:
            local = False
        if local:
            accepted, _ = generate_and_test(form, lambda spelling: machine_service.analyze(spelling, None, fetch=False))
            found = accepted
    rows, seen = [], set()
    for spelling, rules, found_result in found:
        engine = engine_label(found_result)
        for candidate in found_result["machine_candidates"]:
            features = canonical_features(candidate)
            parse = compact_parse(features)
            key = (candidate.get("lemma"), parse, spelling)
            if not candidate.get("lemma") or key in seen:
                continue
            seen.add(key)
            row = {"lemma": candidate["lemma"], "analysis_text": parse, "features": features,
                   "source": engine, "candidate_kind": "machine_analysis", "basis": "machine_analysis",
                   "receipt_id": candidate.get("receipt_id"), "machine_candidate_id": candidate.get("id"),
                   "reason": "Machine parse of the printed form; not a source record."}
            if spelling:
                row.update(normalised_query=spelling, matched_form=spelling, normalisation_rule="+".join(rules),
                           normalisation_note=describe(rules),
                           reason=f"{describe(rules)}: the parser analyses {spelling}; not a source record.")
            rows.append(row)
            if len(rows) >= MAX_ROWS:
                break
    if rows and headword_lookup is not None:
        from .lemma_glosses import attach_lemma_glosses
        table = [{"kind": "word", "id": f"w{i}", "text": form, "form": form, "lemma": row["lemma"],
                  "features": row["features"], "gloss": {}, "status": "selected"} for i, row in enumerate(rows)]
        attach_lemma_glosses({"readings": [{"tokens": table}]}, headword_lookup, form_lemmas=form_lemmas)
        for row, filled in zip(rows, table):
            gloss = filled.get("gloss") or {}
            text = gloss.get("short_text") or gloss.get("text")
            if text:
                row["gloss"] = text
                row["gloss_source"] = gloss.get("source")
            if filled.get("lemma") and filled["lemma"] != row["lemma"]:
                row["parser_lemma"], row["lemma"] = row["lemma"], filled["lemma"]
    return rows
