'use strict';
const $ = (selector, root = document) => root.querySelector(selector);
const el = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; };
let manifest = { themes: [] }, state = {}, csrf = '', manifestSignature = '', activeImage = null, activeTheme = null, toastTimer, jobs = [];
const star = () => { const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.setAttribute('viewBox', '0 0 20 20'); svg.setAttribute('aria-hidden', 'true'); const path = document.createElementNS(svg.namespaceURI, 'path'); path.setAttribute('d', 'm10 1.5 2.6 5.3 5.9.8-4.2 4.2 1 5.8-5.3-2.8-5.3 2.8 1-5.8-4.2-4.2 5.9-.8Z'); svg.append(path); return svg; };
const arrow = () => { const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.setAttribute('class', 'arrow-icon'); svg.setAttribute('viewBox', '0 0 16 16'); svg.setAttribute('aria-hidden', 'true'); const path = document.createElementNS(svg.namespaceURI, 'path'); path.setAttribute('d', 'M3 13 13 3M4 3h9v9'); svg.append(path); return svg; };
function notify(message) { const node = $('#toast'); node.textContent = message; node.hidden = false; clearTimeout(toastTimer); toastTimer = setTimeout(() => { node.hidden = true; }, 4500); }
async function api(path, data) { const response = await fetch(path, data === undefined ? {} : {method:'POST', headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)}); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Please try again.'); return result; }
function themeBusy(id) { return jobs.some(job => job.status === 'running'); }
function studyLabel() { return manifest.orientation === 'landscape' ? 'Landscape watercolour study' : 'Portrait watercolour study'; }
function updateCollectionIdentity() {
 const landscape=manifest.orientation==='landscape';
 document.body.classList.toggle('landscape-collection',landscape);
 const title=manifest.title||(landscape?'Landscape studies':'Nature studies');
 document.title=`Melos — ${title}`;
 $('#collection-name').textContent=title.toLowerCase();
 $('#collection-footer').textContent=`MELOS / ${title.toUpperCase()}`;
 if(landscape){$('#collection-heading').textContent=title;$('#collection-intro').textContent='Your five favourite worlds, extended into two landscape studies each. Explore the full scene, leave a thought, and choose your favourites.';}
 $('#header-crop').closest('label').hidden=landscape;
 if(landscape){$('#header-crop').checked=false;$('#gallery').classList.remove('header-mode');}
}
function updateFavouriteButtons() { document.querySelectorAll('[data-favourite]').forEach(button => {const chosen = Boolean(state[button.dataset.favourite]?.favourite); button.setAttribute('aria-pressed', String(chosen)); $('.favourite-label',button).textContent = chosen ? 'Favourited' : 'Favourite'; button.closest('.painting-card')?.classList.toggle('is-favourite', chosen);}); if (activeImage) { const chosen = Boolean(state[activeImage.id]?.favourite); $('#dialog-favourite').textContent = chosen ? 'Favourited' : 'Favourite'; $('#dialog-favourite').setAttribute('aria-pressed',String(chosen)); } }
async function saveFeedback(themeId, imageId, values) { const result = await api('/api/feedback', {theme_id:themeId,image_id:imageId,...values}); state=result.state; updateFavouriteButtons(); }
function makeCard(theme, painting, index) {
 const card=el('article','painting-card'); if(state[painting.id]?.favourite) card.classList.add('is-favourite');
 const art=el('button','art-button'); art.type='button'; art.setAttribute('aria-label',`Preview ${theme.title}, study ${String(index+1).padStart(2,'0')}`); art.addEventListener('click',()=>openPainting(theme,painting,index));
 if(painting.status==='ready'&&painting.path){const image=el('img'); image.src='/'+painting.path; image.alt=`${theme.title} painting, study ${index+1}`; image.loading='lazy'; image.addEventListener('error',()=>{image.hidden=true; art.append(el('span','placeholder','Painting is arriving'));}); art.append(image);}else{const placeholder=el('span','placeholder',painting.error==='API credits needed'?'Awaiting a little light':painting.status==='failed'?'A new beginning':'A world taking shape');placeholder.append(el('small','',painting.error==='API credits needed'?'API credits needed':painting.status==='generating'?'Being painted':painting.status==='failed'?'Ready to try again':'Coming soon'));art.append(placeholder);}
 const overlay=el('span','header-overlay');overlay.append(el('span','', 'A moment in nature'));art.append(overlay);card.append(art);
 const footer=el('div','card-footer'), caption=el('div','card-caption');caption.append(el('span','card-title',`Study ${String(index+1).padStart(2,'0')}`),el('span',`status ${painting.status}`,painting.status==='ready'?'Watercolour':painting.error==='API credits needed'?'Awaiting credits':painting.status));footer.append(caption);
 const controls=el('div','card-controls'), favourite=el('button','favourite-button');favourite.type='button';favourite.dataset.favourite=painting.id;favourite.append(star(),el('span','favourite-label','Favourite'));favourite.addEventListener('click',async()=>{favourite.disabled=true;try{await saveFeedback(theme.id,painting.id,{favourite:!state[painting.id]?.favourite});}catch(error){notify(error.message);}finally{favourite.disabled=false;}});
 const feedback=el('button','feedback-button','Leave feedback');feedback.type='button';feedback.append(arrow());feedback.addEventListener('click',()=>openPainting(theme,painting,index));controls.append(favourite,feedback);footer.append(controls);card.append(footer);return card;
}
function makeThemeFeedback(theme){const panel=el('div','theme-feedback');panel.hidden=true;const label=el('label','',`A new direction for ${theme.title.toLowerCase()}`);label.htmlFor=`notes-${theme.id}`;const notes=el('textarea');notes.id=label.htmlFor;notes.maxLength=2000;notes.placeholder='Describe the mood, colours, or details you would like to see…';notes.value=state[theme.id]?.notes||'';const actions=el('div','theme-actions');actions.append(el('p','','Creates one new variation with a paid image request. Your notes are saved; existing paintings stay.'));const save=el('button','secondary','Save feedback');save.addEventListener('click',async()=>{save.disabled=true;try{await saveFeedback(theme.id,null,{notes:notes.value});notify('Your feedback is saved.');}catch(error){notify(error.message);}finally{save.disabled=false;}});const regenerate=el('button','primary','Generate one more');regenerate.dataset.regenerate=theme.id;regenerate.disabled=themeBusy(theme.id);regenerate.addEventListener('click',()=>regeneratePainting(theme.id,null,notes.value,regenerate));actions.append(save,regenerate);panel.append(label,notes,actions);return panel;}
function render(){
 updateCollectionIdentity();
 const gallery=$('#gallery'),nav=$('#theme-nav');gallery.replaceChildren();nav.replaceChildren();
 let total=0,ready=0;manifest.themes.forEach((theme,index)=>{const anchor=el('a');anchor.href=`#${theme.id}`;anchor.append(el('small','',String(index+1).padStart(2,'0')),document.createTextNode(theme.title));nav.append(anchor);const section=el('section','theme-section');section.id=theme.id;const heading=el('div','section-heading'),info=el('div'),titleLine=el('div','section-title-line');titleLine.append(el('span','section-number',String(index+1).padStart(2,'0')),el('h2','',theme.title));info.append(titleLine,el('p','',theme.description));const refine=el('button','text-button','Refine this theme');refine.append(arrow());heading.append(info,refine);const grid=el('div','paintings-grid');theme.images.forEach((painting,paintingIndex)=>{grid.append(makeCard(theme,painting,paintingIndex));total++;if(painting.status==='ready')ready++;});const feedback=makeThemeFeedback(theme);refine.setAttribute('aria-expanded','false');refine.addEventListener('click',()=>{feedback.hidden=!feedback.hidden;refine.setAttribute('aria-expanded',String(!feedback.hidden));if(!feedback.hidden)$('textarea',feedback).focus();});section.append(heading,grid,feedback);gallery.append(section);});
 if(!manifest.themes.length)gallery.append(el('p','empty-collection','The collection is being prepared.'));
 if(ready===0&&manifest.themes.some(theme=>theme.images.some(painting=>painting.error==='API credits needed'))){const notice=el('div','generation-notice');notice.append(el('p','','Image generation is waiting for API credits.'),el('span','',`The ${total} planned studies are below. After credits are available, Generate one more creates a painting from your feedback.`));gallery.prepend(notice);}
 $('#ready-count').textContent=String(ready).padStart(2,'0');$('#collection-summary').textContent=`${manifest.themes.length} themes · ${total} studies${ready<total?` · ${ready} ready`:''}`;updateFavouriteButtons();
}
function openPainting(theme,painting,index){activeImage=painting;activeTheme=theme;$('#dialog-theme').textContent=theme.title;$('#dialog-title').textContent=`Study ${String(index+1).padStart(2,'0')}`;$('#dialog-status').textContent=painting.status==='ready'?studyLabel():painting.error==='API credits needed'?'Awaiting credits':painting.status;$('#dialog-prompt').textContent=painting.prompt||'Artist direction will appear with this painting.';$('#painting-notes').value=state[painting.id]?.notes||'';$('#dialog-message').textContent=painting.error||'';const image=$('#dialog-image');image.hidden=painting.status!=='ready'||!painting.path;$('#dialog-placeholder').hidden=!image.hidden;$('#dialog-placeholder').textContent=painting.error==='API credits needed'?'API credits needed':painting.status==='failed'?'Painting has not been generated':'Painting in progress';if(!image.hidden){image.src='/'+painting.path;image.alt=`${theme.title}, study ${index+1}`;}else image.removeAttribute('src');$('#regenerate-image').disabled=themeBusy(theme.id);updateFavouriteButtons();$('#painting-dialog').showModal();$('#close-dialog').focus();}
async function regeneratePainting(themeId,imageId,notes,button){button.disabled=true;try{await saveFeedback(themeId,imageId,{notes});const result=await api('/api/regenerate',{theme_id:themeId,image_id:imageId,notes});jobs.push({job_id:result.job_id,theme_id:themeId,status:'running'});notify('A new painting is on its way. You can keep exploring.');if(activeTheme?.id===themeId)$('#dialog-message').textContent='Creating one new painting. It will appear in this collection when ready.';document.querySelectorAll(`[data-regenerate="${themeId}"]`).forEach(node=>{node.disabled=true;});}catch(error){notify(error.message);button.disabled=false;}}
$('#painting-notes').maxLength=2000;
$('#close-dialog').addEventListener('click',()=>$('#painting-dialog').close());$('#painting-dialog').addEventListener('click',event=>{if(event.target===$('#painting-dialog')){const bounds=event.target.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)event.target.close();}});
$('#dialog-favourite').addEventListener('click',async()=>{const button=$('#dialog-favourite');button.disabled=true;try{await saveFeedback(activeTheme.id,activeImage.id,{favourite:!state[activeImage.id]?.favourite});}catch(error){notify(error.message);}finally{button.disabled=false;}});
$('#save-notes').addEventListener('click',async()=>{const button=$('#save-notes');button.disabled=true;try{await saveFeedback(activeTheme.id,activeImage.id,{notes:$('#painting-notes').value});$('#dialog-message').textContent='Your feedback is saved.';}catch(error){$('#dialog-message').textContent=error.message;}finally{button.disabled=false;}});
$('#regenerate-image').addEventListener('click',()=>regeneratePainting(activeTheme.id,activeImage.id,$('#painting-notes').value,$('#regenerate-image')));
$('#header-crop').addEventListener('change',event=>$('#gallery').classList.toggle('header-mode',event.target.checked));
function syncOpenPreview(){
 if(!activeImage||!$('#painting-dialog').open)return;
 const theme=manifest.themes.find(item=>item.id===activeTheme.id),painting=theme?.images.find(item=>item.id===activeImage.id);
 if(!painting)return;
 const changed=painting.status!==activeImage.status||painting.path!==activeImage.path||painting.error!==activeImage.error;
 activeTheme=theme;activeImage=painting;
 if(!changed)return;
 $('#dialog-status').textContent=painting.status==='ready'?studyLabel():painting.error==='API credits needed'?'Awaiting credits':painting.status;
 const image=$('#dialog-image'),show=painting.status==='ready'&&painting.path;
 image.hidden=!show;$('#dialog-placeholder').hidden=Boolean(show);
 if(show){image.src='/'+painting.path;image.alt=`${theme.title} painting`;}else image.removeAttribute('src');
 $('#dialog-placeholder').textContent=painting.error==='API credits needed'?'API credits needed':painting.status==='failed'?'Painting has not been generated':'Painting in progress';
 $('#dialog-message').textContent=painting.error||'';
}
async function refresh(){try{const[next,nextJobs]=await Promise.all([api('/api/manifest'),api('/api/jobs')]);const signature=JSON.stringify(next);jobs=nextJobs.jobs||[];if(signature!==manifestSignature){const drafts=new Map([...document.querySelectorAll('.theme-feedback')].map(panel=>{const area=$('textarea',panel);return[area.id,{value:area.value,open:!panel.hidden}];}));manifest=next;manifestSignature=signature;render();document.querySelectorAll('.theme-feedback').forEach(panel=>{const area=$('textarea',panel),draft=drafts.get(area.id);if(draft){area.value=draft.value;panel.hidden=!draft.open;panel.parentElement.querySelector('.section-heading>.text-button').setAttribute('aria-expanded',String(draft.open));}});syncOpenPreview();}document.querySelectorAll('[data-regenerate]').forEach(button=>{button.disabled=themeBusy(button.dataset.regenerate);});if(activeTheme)$('#regenerate-image').disabled=themeBusy(activeTheme.id);}catch(error){/* Preserve drafts and the visible collection during transient polling failures. */}}
async function start(){try{const[session,saved]=await Promise.all([api('/api/session'),api('/api/state')]);csrf=session.csrf_token;state=saved;await refresh();setInterval(refresh,4000);}catch(error){notify('The gallery could not connect. Reload this page to try again.');}}
start();
