"""Build web variants of the hero paintings.

Source JPEGs live in assets/source/ (not served). For each painting this writes
AVIF + WebP at a ladder of widths, plus a small WebP thumbnail, with a content
hash in every filename so the files can be cached forever. It then writes
js/images.js, which the site imports to pick the right size at runtime.

Run from the repo root:  python tools/build_images.py
"""
from hashlib import sha1
from io import BytesIO
from pathlib import Path
import json

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "source"
OUT = ROOT / "assets" / "paintings"
WIDTHS = [480, 960, 1600, 2400]
THUMB = 160
FORMATS = {"avif": dict(quality=58, speed=4), "webp": dict(quality=80, method=6)}


def encode(im, fmt, **opts):
    buf = BytesIO()
    im.save(buf, fmt.upper(), **opts)
    return buf.getvalue()


def write(stem, data, ext):
    name = f"{stem}.{sha1(data).hexdigest()[:8]}.{ext}"
    (OUT / name).write_bytes(data)
    return f"assets/paintings/{name}"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.iterdir():  # generated output only; sources live elsewhere
        old.unlink()
    manifest, total = {}, 0
    for src in sorted(SRC.glob("*.jpg")):
        im = ImageOps.exif_transpose(Image.open(src)).convert("RGB")
        w0, h0 = im.size
        widths = [w for w in WIDTHS if w < w0] + [min(w0, WIDTHS[-1])]
        variants = []
        for w in widths:
            v = im.resize((w, round(h0 * w / w0)), Image.LANCZOS) if w != w0 else im
            files = {}
            for ext, opts in FORMATS.items():
                data = encode(v, ext, **opts)
                total += len(data)
                files[ext] = write(f"{src.stem}-{w}", data, ext)
            variants.append({"w": w, **files})
        t = im.copy(); t.thumbnail((THUMB, THUMB * 2))
        thumb = encode(t, "webp", quality=72)
        total += len(thumb)
        manifest[src.stem] = {"aspect": round(w0 / h0, 4), "variants": variants,
                              "thumb": write(f"{src.stem}-thumb", thumb, "webp")}
        dsrc = SRC / "depth" / f"{src.stem}.png"   # from tools/build_depth.py; drives the mosaic relief
        if dsrc.exists():
            depth = encode(Image.open(dsrc).convert("L"), "webp", quality=90)
            total += len(depth)
            manifest[src.stem]["depth"] = write(f"{src.stem}-depth", depth, "webp")
        print(f"{src.stem}: {w0}x{h0} -> {[v['w'] for v in variants]}")
    (ROOT / "js" / "images.js").write_text(
        "// Generated by tools/build_images.py. Do not edit.\n"
        f"export const IMAGES = {json.dumps(manifest, indent=2)};\n", encoding="utf-8")
    print(f"total written: {total / 1024:.0f} KB")


if __name__ == "__main__":
    main()
